# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 91, 601))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 91, 601))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layoutBtn_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layoutBtn_2.setContentsMargins(0, 0, 0, 0)
        self.layoutBtn_2.setObjectName("layoutBtn_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 0, 711, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetAdd = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widgetAdd.setObjectName("widgetAdd")
        self.comboBoxType = QtWidgets.QComboBox(self.widgetAdd)
        self.comboBoxType.setGeometry(QtCore.QRect(30, 40, 121, 22))
        self.comboBoxType.setObjectName("comboBoxType")
        self.label = QtWidgets.QLabel(self.widgetAdd)
        self.label.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.label.setObjectName("label")
        self.lineEditPostUrl = QtWidgets.QLineEdit(self.widgetAdd)
        self.lineEditPostUrl.setGeometry(QtCore.QRect(30, 100, 461, 22))
        self.lineEditPostUrl.setObjectName("lineEditPostUrl")
        self.label_2 = QtWidgets.QLabel(self.widgetAdd)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 131, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditNum = QtWidgets.QLineEdit(self.widgetAdd)
        self.lineEditNum.setGeometry(QtCore.QRect(170, 40, 41, 22))
        self.lineEditNum.setObjectName("lineEditNum")
        self.label_3 = QtWidgets.QLabel(self.widgetAdd)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 55, 16))
        self.label_3.setObjectName("label_3")
        self.lineEditItemNum = QtWidgets.QLineEdit(self.widgetAdd)
        self.lineEditItemNum.setGeometry(QtCore.QRect(230, 40, 91, 22))
        self.lineEditItemNum.setObjectName("lineEditItemNum")
        self.label_4 = QtWidgets.QLabel(self.widgetAdd)
        self.label_4.setGeometry(QtCore.QRect(230, 20, 101, 16))
        self.label_4.setObjectName("label_4")
        self.lineEditImgUrl = QtWidgets.QLineEdit(self.widgetAdd)
        self.lineEditImgUrl.setGeometry(QtCore.QRect(30, 160, 461, 22))
        self.lineEditImgUrl.setObjectName("lineEditImgUrl")
        self.label_5 = QtWidgets.QLabel(self.widgetAdd)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 161, 16))
        self.label_5.setObjectName("label_5")
        self.pushButtonAdd = QtWidgets.QPushButton(self.widgetAdd)
        self.pushButtonAdd.setGeometry(QtCore.QRect(30, 190, 101, 31))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.textEditTest = QtWidgets.QTextEdit(self.widgetAdd)
        self.textEditTest.setGeometry(QtCore.QRect(30, 260, 571, 321))
        self.textEditTest.setObjectName("textEditTest")
        self.gridLayout.addWidget(self.widgetAdd, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Тип"))
        self.label_2.setText(_translate("MainWindow", "Ссылка на пост"))
        self.label_3.setText(_translate("MainWindow", "№"))
        self.label_4.setText(_translate("MainWindow", "Кол-во позиций"))
        self.label_5.setText(_translate("MainWindow", "Ссылка на изображение"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Добавить"))
